### ISSUE TITLE
Legacy 模式启动的前提下，Windows 10 Version 2004 下 vtoydump 不按预期工作

### ISSUE THREAD

**Issue by HikariCalyx** [ventoy/vtoydump#3]
检查发现和我构建的PE没关系。
Legacy 模式下，即便是在原版的安装镜像下手动调用命令提示符执行 vtoydump 也不会返回镜像路径。UEFI 模式下就可以正常返回路径。

手头暂时没有 Version 1903 / 1909 的安装镜像测试，但在 Version 1809 下执行同样的 vtoydump.exe 构建可以正常返回路径。

![legacy](https://user-images.githubusercontent.com/29157608/85729339-4e199e80-b72b-11ea-9ac0-88187767d663.jpg)
![uefi](https://user-images.githubusercontent.com/29157608/85729359-52de5280-b72b-11ea-9412-78d8192833a5.jpg)

**Comment by ventoy** [comment]
执行 vtoydump -v 看看

**Comment by HikariCalyx** [comment]
下图是 Version 1909 (18363.900) 的镜像的返回结果。
![IMG_20200626_072215](https://user-images.githubusercontent.com/29157608/85805812-f22d3500-b77f-11ea-96bc-151272ac6d96.jpg)

下图是 Version 2004 (19041.331) 的镜像的返回结果。
![IMG_20200626_072452](https://user-images.githubusercontent.com/29157608/85805820-f48f8f00-b77f-11ea-91cd-cbbc933998eb.jpg)

看起来是在 19041 下被误判为 EFI 启动模式了。

**Comment by HikariCalyx** [comment]
另外，正常系统下，wpeutil UpdateBootInfo 命令可以正确判断是 Legacy 启动模式，但 AIDA64 下都显示为 UEFI Boot 启动模式。
不知道 Version 2004 做了什么变化……
![ventoy_legacy](https://user-images.githubusercontent.com/29157608/85807072-5e5d6800-b783-11ea-8394-f47669710c99.png)

**Comment by HikariCalyx** [comment]
新更新的 vtoydump 解决了此问题。关闭issue。
